apiVersion: v1
kind: ConfigMap
metadata:
  name: tlsprobe-config
data:
  config.yml: |
    autoDiscover:
      - name: yunpian-aliyun
        type: AliDNS
        options:
          accessKeyId: ""
          accessKeySecret: ""
      - name: qipeng-dnspod
        type: DNSPod
        options:
          secretId: ""
          secretKey: ""
    hostScannersConfig:
      - host: www.baidu.com
        TLSOptions:
          timeout: 3000
      - host: www.google.com
        TLSOptions:
          timeout: 3000
      - host: www.baidu.cn
        TLSOptions:
          timeout: 3000
          skipVerify: true
    listenAddr: "0.0.0.0:9217"
    maxConnections: 1500
    maxConnectConnections: 1500
